SELECT
  Do_you_think_that_discussing_a_mental_health_disorder_with_your_employer_would_have_negative_consequences_,
  COUNT(*) AS total,
  ROUND(((COUNTIF(Have_you_ever_sought_treatment_for_a_mental_health_issue_from_a_mental_health_professional_ = 1)/ COUNT(*))* 100), 2) AS pct_sought_treatment
FROM `true-elevator-380814.mental_health_project.mental_health_in_tech_2016`
WHERE Do_you_think_that_discussing_a_mental_health_disorder_with_your_employer_would_have_negative_consequences_ IS NOT NULL
  AND Have_you_ever_sought_treatment_for_a_mental_health_issue_from_a_mental_health_professional_ IS NOT NULL
GROUP BY Do_you_think_that_discussing_a_mental_health_disorder_with_your_employer_would_have_negative_consequences_
ORDER BY pct_sought_treatment DESC
